// ============================================================
// REFERANS DANIŞAN ANALİZLERİ — Few-shot örnekler
// Sistem promptunda Claude'a ton/üslup rehberi olarak verilir.
// Claude bu metinlerden şunları öğrenir:
//   - 2. tekil şahıs (siz/sizin)
//   - Akıcı, uzun paragraflar
//   - Sayıları birbirine örerek yorumlama
//   - Soy/aile karması vurgusu
//   - Somut ritüel önerileri
//   - Sıcak ama dürüst anlatım
// NOT: Bu metinler yalnızca tonu öğretmek içindir. Üretilen
// PDF içeriğinde herhangi bir kişi veya marka adı geçmez.
// ============================================================

export const EXAMPLE_ANALYSES = [
  {
    birthDate: "22.12.2000",
    text: `22'lerde genç ruhlar olur, çocuk enerjisinde olurlar. Bu dünyaya özgürlük için gelirler. Özgürlüklerine çok düşkündürler, yenilikçidirler, keşif için gelmiş gibidirler bu dünyaya. 22 aslında 0'dır. Yani ruh 0'dan gelir ve keşif yapar. Özellikle 12. ayda doğan ruhlar da genç ruh enerjisi taşır ve soyları birleştirmek için gelir. Sizde iki tane genç ruh birleşmiş. Belki de bu yüzden misyonunuz 9'dur; biraz büyümeniz, olgunlaşmanız için. Çünkü 22 de çocuk enerjisidir, 12 de. Bu enerji çok fedakâr, hevesli, oynayıp bırakan bir enerjidir.

9 ise olgunlaşmadır. 9, misyon olarak size verilmişse, ileride insanlığa derin bilgileri aktarmanız anlamına gelir. Zaten hayat karmanız da 5 olduğu için derin bilgileri öğretme potansiyeliniz var. Ama bu hemen olacak bir şey değil. Bu misyon genelde 38–40 yaşlarından sonra, 40–45–50 yaş aralığında açılır. 9 enerjisi bilgi paylaşır. Sizin göreviniz insanları bilgiyle dengeye getirmek, 14 enerjisiyle huzur vermektir.

14'ün yanında insanlar kendini rahat ve huzurlu hisseder. Bu bir melek enerjisidir. Ama 14'ün kendisi huzursuz olabilir. İçinde hep bir "geç kalıyorum" duygusu olur. Zamanla ilgili bir baskı hisseder. "Yetişemem, zaman yetmez" düşüncesi olabilir. Ayrıca 14'te abartı enerjisi vardır. Bu yüzden dengeyi bozmamak gerekir. Bazen çok verici olabilirsiniz, aşırı empati yapabilirsiniz, karşı tarafı fazla hissedebilirsiniz. Ama burada 14 size der ki: "Dengeyi bozuyorsun, kendini feda ediyorsun." Bu yüzden kendinizi kurban rolüne sokmamalısınız.

9 enerjisi de yalnız kalmamalıdır. Çünkü 9'lar yalnızlığa meyilli olur. 22 ise özgürlüğe meyillidir. Bu ikisi birbirine zıt çalışır. 22 çocuk gibidir, 9 ise yaşlı ruh gibidir. Biri rahatlığı, konforu, özgürlüğü sever. 22 sabit saatli, kuralcı işlerde çok kalmak istemez. Daha özgür çalışmak ister. Kısıtlanmayı sevmez, baskı altında olmayı sevmez. Ama 22'lerin hayatında zaman zaman kısıtlanma ve baskı teması olur. Ya aile tarafından ya çevre tarafından sınırlandırılırlar. Çünkü 22'nin görevi o aileye özgürlüğü öğretmektir. Yani siz bu aileye özgürlük getirmek için doğmuşsunuz. Onlara "insan nasıl özgür olur, nasıl kendi başına bir şey yapar" bunu göstermek için. Ama kendinizi de kısıtlamamalısınız. Çünkü 22'nin negatifinde kişi kendi kendini kısıtlar ve potansiyelini tam gösteremez. Bu da nereden gelir? Karmasındaki 6'dan ve mükemmeliyetçilikten. "Mükemmel olayım sonra başlayayım" düşüncesi olur. Ama böyle bir şey yoktur. Önce harekete geçmek gerekir ki sonra mükemmelleşme gelsin.

Bir de 22 enerjisi olanların çocuk sahibi olması önemlidir. 22 sayısı özellikle çok çocuklu kadınların haritalarında sık görülür. Çünkü 22 zaten çocuk enerjisidir ve yeni başlangıçları temsil eder. 22'lere önerimiz; zaman zaman yüksek yerlere çıkmaları, doğada vakit geçirmeleri, özellikle kayalık alanlar gibi yerlerde bulunmalarıdır. Ayrıca hayvanlarla temas etmeleri, onları beslemeleri çok faydalıdır. Zaten sizde hem 2 hem 22 enerjisi olduğu için bu daha da önemlidir. 22'ler hayvan dostudur. Ya çok korkarlar ya da çok bağ kurarlar. Çünkü 22'nin sembolünde bir köpek vardır. Aslında o köpek onun sadık dostudur.

22, kayanın başında duran bir çocuk gibidir. Bazen farkında olmadan öyle bir adım atar ki, bir adım daha atsa düşecek aslında… Ama ayağının altını görmez. Orada bir köpek vardır, onu durdurur: "Yapma." Çünkü 22'nin içinde bu vardır; özgür ruhuyla kendi bildiğini yapmak ister. Sanki hayatında onu durduran birileri olur. Ama başının üstünde güneş olduğu için 22 aynı zamanda çok şanslıdır. Zaten sizin haritanızda şans enerjileri çok güçlü. Çünkü 22'nin de güneşi var, 12'nin de güneşi var. 10'lar ise zaten ilahi koruma altındaki enerjilerdir. 12'nin de başının üstünde güneş vardır, 22'nin de. Bu ne demek? Güneş sizi parlatmak istiyor. Siz bu hayatta parlamak için gelmişsiniz.

Ama zaman zaman çok güçlü spiritüel enerjileriniz var. İster hukukla ilgili bir iş yapın, ister sanatla… bir noktada su çalışmaları, mantralar, yoga gibi alanlardan geçmeniz gerekir. Aksi halde bu sayılar sizi biraz zorlayabilir. Bazen hayat şifacıyı şifaya muhtaç bırakır. Öyle bir olay yaşarsınız ki, "neden böyle oldu?" diye kendi yolunuzu ararsınız ve bu yola girersiniz. Sizin yolunuz tamamen şifacılık olmayabilir ama ruhunuzda çok güçlü "2" enerjileri var. 2; empati ve duygudur. Sizde 2, 12'nin içinde 2, 22'nin içinde 2, 20'nin içinde 2… Yani çok fazla duygu enerjisi var. Bu da insanların duygularıyla çalışabileceğiniz anlamına gelir.

Mesela bu haritadan çok iyi bir çocuk doktoru bile çıkabilirdi. Çünkü sizin şefkat enerjiniz çok yüksek. Partnerinize bile annelik yapabilirsiniz; "yedin mi, içtin mi, üşüme" gibi… Ama işte burada 14 devreye giriyor ve diyor ki: "Sen abartıyorsun." Sen partnerinin annesi değilsin. Sen dünyanın kurtarıcısı değilsin. Herkese fedakârlık yapmak zorunda değilsin. Ama aslında karmasında 6 olduğu için kişi onaylanmak ister. Fedakârlık yapmasının altında bu vardır. "Beni görsünler, beni takdir etsinler" isteği… Ama fazla fedakârlık yaptığında kimse bunu görmez. Hatta sonunda "yapmasaydın" derler. Bu özellikle 12'nin kaderinde vardır. Çok verir, çok fedakârdır. Sonra da kırılır, "ben bunu yaptım, bana bunu yaptılar" diye üzülür. Ama karşı taraf "ben senden istemedim ki" der. O yüzden bu kadar fedakâr olmamalısınız.

Evet, hizmet enerjiniz çok güçlü. Siz bu dünyaya hizmet etmeye gelmişsiniz 12 ile. Aynı zamanda statü kazanma potansiyeliniz var. 12'ler, özellikle Aralık doğumlular ya statülü bir ailede doğar ya da kendileri statü kazanır. Öyle bir noktaya gelir ki adı bilinir, saygı görür. Ama burada önemli olan; hizmet ederken dengeyi korumak. Çünkü bazen maddiyat konusunda hakkınızı alamayabilirsiniz. Para istemekte zorlanabilirsiniz. Bir iş yaparsınız ama "ayıp olur" diye ücret talep edemezsiniz. Hatta biri gelip "son param bu" dese, inanıp verirsiniz. Bu yüzden sizden iyi bir satışçı çıkmaz. Manipülasyon yapamazsınız, satış baskısı kuramazsınız. O sizin alanınız değil. Sizin alanınız daha çok diplomasi. İki insanı, iki tarafı barıştıran, arabulucu olan, ortamı yumuşatan, huzur getiren kişi olursunuz.

Size tavsiyem; en azından yılda bir kez soyunuz adına bir kurban kestirmeniz. Çünkü siz de 10'lu bir enerjiden gelmişsiniz. Demek ki bu soyda çözülmesi gereken bir şey var. Karmik yük çok ağır değil ama nokta atışıdır. Yani bir yerden kökten vurur ve "mesele burada" der. Yanında 10 olduğu için tekrar eden kader döngüsü var. Yani dikkat etmezseniz, soyunuzdan birinin hayatını tekrar edebilirsiniz. Mesela o soyda evlenmeyen biri olabilir, çocuğu olmayan biri olabilir, aldatılan bir kadın olabilir… Siz de farkında olmadan aynı döngüyü yaşayabilirsiniz.

Bu yüzden yapılması gereken şey; soyla barışmak, kabul etmek ve negatifi şifalandırmak. Yani içten bir şekilde demek ki: "Çok teşekkür ederim ama sizin yaşadığınız döngüleri ben devam ettirmek istemiyorum." Mümkünse yılda bir kez ya kurban kestirin ya da bir yardım yapın. Özellikle çocuklara yönelik yardım çok uygun olur, çünkü haritanızda çocuk enerjisi yüksek. Bu yardımı soyunuz adına yapmalısınız. Çok büyük olmasına gerek yok ama niyet çok önemli. Yapmadan önce şöyle niyet edebilirsiniz: "Allah'ım, ata ve anne soyumun günahlarını bağışla. Bu soylarda ne haksızlıklar olduysa, ne karmalar yaşandıysa, bilerek ya da bilmeyerek ne hatalar yapıldıysa, ben onların adına senden özür diliyorum. Bugün anladım ki hem kendi karmamın hem de soyumun şifalanması gerekiyor. Bu yaptığım hayrın sevabı yedi nesilime yazılsın." Bu niyetle yardım yapabilirsiniz. Verdiğiniz şeyleri 7 ya da 9 parça halinde vermeniz önerilir. Ve kesinlikle akrabalara değil, tanımadığınız insanlara verilmelidir.

Bir diğer konu; 20 enerjisinde yargılama vardır. Bu bir "mahkeme" enerjisidir. Zaten 20. arkana da bunu temsil eder. Bu yüzden kimseyi yargılamamaya dikkat etmelisiniz. Özellikle ailenizi… "O okumadı, o şöyle yaptı" gibi içsel yargılardan uzak durmalısınız. Aynı zamanda kin tutmamalısınız. Çünkü 20 hem kin tutma hem yargılama hem de sevdiklerini kaybetme korkusunu taşır. İçinde bir ölüm korkusu vardır. Bu yüzden ölümün bir son değil, bir başlangıç olduğunu kabul etmek gerekir. Çünkü 20 bu konuda zorlanır, özellikle sevdiği kişiler söz konusu olduğunda. Bir diğer önemli şey; aileyle ilişkileri sağlam tutmak. 20 köklerinden kopmamalıdır.

Size ayrıca önerim: İki tane soy ağacı hazırlayın. Biri baba tarafı, biri anne tarafı için. Ve özellikle araştırın. Ailenizde neler yaşanmış? Ama pozitifleri değil, negatifleri… Kim erken ölmüş, kim iflas etmiş, kimin çocuğu olmamış, kim kaza geçirmiş, kim savaşa gidip dönmemiş… Bunları tek tek yazın. Hepsini o soy ağacına ekleyin. Çünkü bu farkındalık, karmayı çözmenin ilk adımıdır. Sonra her ayın 20'sinde bir ritüel yapın. Mesela bir masa kurun, karşısına geçin. Özellikle savaşa gidenler için ağaç dikin. Deyin ki: "Allah'ım, savaşa gidip geri dönemeyen atalarım için… kazada ani vefat edenler için… onların ruhları ışığa ulaşsın." Çünkü ani ölen ruhlar bazen o geçişi tamamlayamaz. Siz onların adına dua edersiniz. Sonrasında bunun karşılığında bir sadaka verirsiniz. Bir çocuğa, bir yaşlıya yardım edebilirsiniz ya da bir ağaç dikersiniz. Ağaç dikmek doğaya bir hediyedir. Özellikle çam ya da meyve ağacı olabilir.

Aynı şekilde "2" enerjiniz için sokak hayvanlarını beslemeniz çok önemli. Bir gün babanızın adına, bir gün annenizin adına yapın. Mesela şöyle niyet edin: "Allah'ım, babamın bilerek ya da bilmeyerek yaptığı hataları bağışla. Bu yaptığım iyilik onun adına yazılsın." Sonra aynı şeyi anneniz için yapın. Bu enerjiler özellikle hayvanlar üzerinden çok güzel çalışır. Sizden bir şey eksilmez ama size çok güçlü bir dönüş olarak geri döner.

Ayrıca mutlaka spor yapın. Çünkü 7 enerjisi bedene iyi bakmayı ister. 7 der ki: "Bedenine sahip çık, hedeflerine odaklan ama kendini kimseye kurban etme." Çünkü 7'nin içinde bir savaş enerjisi vardır. Soyunuzda savaş, kaza, ani kayıplar olabilir. Özellikle anne-baba soylarında savaşa gidenler, kazada ölenler olabilir. Bu yüzden hem ruhsal hem fiziksel dengeyi korumak sizin için çok önemli.

Şimdi sizin yaşam misyonunuz 14. Bu bir "melek enerjisi"dir. Yani siz bu dünyaya huzur getirmeye gelmişsiniz. İnsanlar sizin yanınızda kendini iyi hisseder. Ama negatifinde 14 sabırsızdır, dengesizdir. Sürekli "geç kalıyorum" hissi olur. Zamanla yarışır, hep saate bakar, acele eder. 14'ün içinde su elementi olduğu için suyla çalışmanız çok faydalı olur. Her sabah bir bardak su alın ve niyet okuyun. Mesela şöyle başlayabilirsiniz: "Ya Rabbim, kadın enerjimi kabul ediyorum. İyi ki bu dünyaya kadın olarak geldim. Kendimi değerli hissediyorum. Hedeflerime kolaylıkla ulaşıyorum. Anda kalıyorum. Yaradan'a, kaderime ve şansıma güveniyorum." Sonra hayatınızda ne istiyorsanız onu suya söyleyin ve için.

Sizin bir diğer sayınız 9. 9 enerjisi zeka verir, bilgelik verir. Ama bazen şöyle bir durum olur: "Ben biliyorum, karşımdaki bilmiyor." 9'lar gerçekten zeki olur ama bu yüzden karşısındaki insanlara tahammülü azalabilir. Bilgisiz insanlara karşı sabırsız olabilir. Bu yüzden 9'un partner bulması zordur. Çünkü sıradan bir ilişki istemez. Ruh eşi ister. Sırf evlenmiş olmak için evlenmez. Eğer yanlış biriyle evlenirse, evliliğin içinde yalnızlık yaşar. Bu yüzden siz de niyetlerinize şunu ekleyin: "Hayatıma olgun bir ruh eşi geliyor. Onunla düşüncelerimi, ruhumu paylaşıyorum. Birlikte ruhsal olarak büyüyoruz." Çünkü sizin enerjiniz (14 ve 9) birlikte meditasyon yapabilecek, ruhsal olarak uyumlu bir partner ister. 27 yaşından sonra zaten bu ilginiz daha da artacak. Numeroloji, astroloji, spiritüel konular sizi daha çok çekecek. Eğer karşı taraf "bunlar ne?" derse, uyum yakalayamazsınız. O yüzden sizin gibi düşünen, meditasyona açık, ruhsal tarafı olan birini seçmeniz gerekir.

Sizin yolunuz aşırı para ve kariyer odaklı bir yol değil. Daha çok aile, duygular, bağ kurma ve ruhsal derinlik üzerine kurulu. Çünkü sizde "2" enerjisi çok güçlü. Bu da annelik, şefkat, empati ve duygusal bağ demektir. Yani siz şu an anne olmadığınız için bu fedakârlık enerjinizi tam hissetmiyor olabilirsiniz. Ama anne olduktan sonra bu çok daha güçlü ortaya çıkacak. Çünkü sizde 22, 12 ve 2 var. Bunların hepsi annelik ve fedakârlık enerjisini artırır. Ama burada önemli bir uyarı var: Anne olduktan sonra kariyerinizi tamamen feda etmeyin. 22 ve 12'de fedakârlık çok güçlüdür, kişi kendini tamamen başkaları için bırakabilir. Ama bu dengeyi kurmanız gerekir.

Bir de 6 enerjisi… 6 sevdi mi çok derin sever. Sevdiği için her şeyi yapar, her şeyden vazgeçebilir. Bu yüzden 6'lara hep şunu söyleriz: Bir işi ya da bir insanı seçerken tek kriteriniz "seviyor muyum?" olsun. Aile istedi diye bir ilişkiye girmeyin. Aşık olmadığınız bir işi de yapmayın. Çünkü 6, aşık olmadığı bir işte duramaz. Bir süre sonra bırakır. Aşık olmadıkça sürekli şikayet eder, kusur bulur, kendini yorar, mükemmel olmaya çalışır. 6 neyi sever? Estetiği. Kendine bakmayı, güzel görünmeyi, saçını, makyajını, bakımını… yani kadınsı enerjileri sever. Eğer bu estetik tarafını beslemezseniz enerjiniz düşer. Modunuz düşer, hayattan keyif alamazsınız. Pozitif yaşadığınızda ise tam tersi olur: enerjiniz yükselir.

22 de der ki: "Beni çok zorlamayın." Çok çalıştığında zihni yorulur. Biraz oyun ister, eğlence ister. Bu yüzden arada kendinize izin verin. Eğlenin, gezin, çocuk gibi vakit geçirin. İçinizde bir çocuk var, onu beslemeniz lazım. Çünkü 22 bazen kendini bir şeye hapseder: kariyere, aileye, paraya… Aslında kimse onu zorlamıyordur, kendini kendisi hapseder. "Sona kadar götürmeliyim, bitirmeliyim" diye kendini sıkıştırır. Ama sistem ona der ki: "Sen özgürsün." 22'nin görevi bağlardan özgürleşmektir. Ama kendisi bağlanmayı sever. Bu yüzden size öneri: Öyle bir iş kurun ki, ileride size rahatlıkla kazanç getirsin. Çünkü uzun vadede saatli, çok yoğun çalışmayı istemeyeceksiniz.

Ayrıca 22 enerjisi çocuklarla ilgili projelerde çok başarılı olur. Çocuklara yönelik bir şey yaptığınızda çok iyi sonuç alırsınız. Çünkü ruhunuzda zaten o çocuk enerjisi var. Yardım etmeniz gereken alanlar da belli: Çocuklar, hayvanlar, yaşlılar. Zaman zaman yardımlarınızı bu gruplara yaparsanız enerjiniz çok dengelenir.

Sizin hem yaşam misyonunuz hem de toplam enerjiniz 9. 9 tamamlanma demektir. Ruhsal olarak olgunlaşma demektir. Ama burada ilginç bir zıtlık var: Bir yanda 9 (olgun, bilge), bir yanda 22 (çocuk, özgür ruh). Bu gerçekten yorucu olabilir. İşte bu yüzden size 14 verilmiş: denge kurmanız için. Yani ne tamamen 22 gibi rahat, umursamaz olun, ne de tamamen 9 gibi yalnız, kimseyi beğenmeyen, ağır bir enerjiye girin. Sistem diyor ki: sen bu ikisinin ortasını bulmalısın. Bazen fazla empatiye gidiyorsunuz, bazen kendinizi kurban ediyorsunuz, bazen de "ben biliyorum" tarafına geçiyorsunuz. Ama dengeyi kurmanız gerekiyor.

Ve şunu da açıkça söyleyelim: Evet kariyer önemli ama hayat sadece kariyer değil. 22'nin en önemli görevlerinden biri çocuk sahibi olmak, 6 ve 2'nin en önemli görevi ise annelik enerjisini yaşamak. Yani hayat size diyor ki: "Her şeyi dengele. Kariyer de olsun, ama aile ve annelik enerjisini de ihmal etme." Halbuki ileride sizin göreviniz insanlara derin bilgi vermek. Öyle yüzeysel değil, gerçekten derin bilgiler… Bu yüzden bunu şimdiden bilip hazırlanmanız gerekiyor.

5 enerjisi ne ister? Sürekli öğrenmek. "Ben üniversite okudum, yeter" diyemezsiniz. Hayır… kurs, eğitim, seminer, workshop… sürekli öğrenmeniz gerekir. Siz sayılarınızı pozitif yaşadıkça şunu göreceksiniz: İstediğiniz, hayal ettiğiniz şeyler yavaş yavaş gerçekleşmeye başlayacak. Ama burada önemli bir nokta var: Evliliği çok ertelemeyin. İlişki ve aile konusu önemli. Ayrıca hangi çakranızda blokaj var, onları da çalışmanız gerekecek.

Bu haritanın sizden istediği şeyler şudur: Empatiniz çok güçlü ama abartmayın. Kariyeriniz olabilir ama anneliği unutmayın. Yalnız kalmayın, sosyal olun. Özellikle 6 enerjisi sosyal çevre ister. Partiler, ortamlar, görünür olmak… bunlar önemli. Belki ileride Instagram ya da TikTok gibi platformlarda konuşmak zorunda kalacaksınız. Ama ne olacak? 22 diyecek: "Aman görünmeyeyim." 6 diyecek: "Acaba ne desem, mükemmel mi?" Ama sistem diyor ki: Konuşacaksın. Görünür olacaksın. Çünkü bu sizin yolunuz. 22 enerjisi aynı zamanda yurt dışı, kozmik enerji, teknoloji ile de bağlantılıdır. 22'ler genelde yurt dışına açılır, teknolojiye yatkın olur, yapay zeka ve modern sistemlere ilgisi olur. Hatta bazen uzay, gezegenler, "uzaylılar var mı?" gibi konulara bile merak duyabilirler. Çünkü 22 çok farklı bir enerjidir. Hem başlangıçtır hem sondur. Karmik sistemde en büyük sayıdır. 22'den sonrası yoktur. Bu yüzden 22 ile gelen insanlar özel bir misyona sahiptir. Ve sizin misyonunuz da şu: insanlara huzur vermek (14), denge getirmek, derin bilgilerle onların ruhuna dokunmak. Yani bu sadece yüzeysel bir yol değil. Gerçekten insanları içten anlayan ve dönüştüren bir yol.`
  },

  {
    birthDate: "15.04.1996",
    text: `Bu haritada çocuklar ve kadınlarla ilgili bir proje enerjisi çok belirgin. 22 zaten çocuk enerjisidir, 3 de yine çocuk ve üretkenlik alanını taşır. O yüzden kadınlarla, annelerle, çocuklarla ilgili hangi iş olursa olsun sizin elinizde canlılık kazanır. Kafanızda çocuklara ve annelere dönük bir alan, bir proje, bir merkez, bir sosyal fikir oluşuyorsa bu tesadüf değil; haritanın söylediği şeydir. Çünkü sizin enerjiniz klasik anlamda yalnızca "ev kadını" olmak isteyen bir enerji değil. Burada 3'ler, 4'ler, 15, 19, yani görünmek, parlamak, dikkat çekmek, etkili olmak, sahneye çıkmak, kendi alanında fark edilmek isteyen bir yapı var. Sizde güneş gibi parlamak isteyen bir enerji var; ama bu enerji hayatın belli dönemlerinde bastırılmışsa içeride agresyona, huzursuzluğa, ev içinde baskıya dönüşebilir. Çünkü dışarıda parlayamayan güneş içeride sertleşir. Bu yüzden bu harita size açıkça diyor ki: görünmez kalmayın. Potansiyelinizi kapatmayın. Çünkü kapatırsanız içinizdeki güç negatif çalışır.

İlk karmalarınıza baktığımda burada 11, 19 ve 15 gibi ateşli ve yoğun rakamlar var. Bu kombinasyon çocukluktan 28 yaşa kadar kişiye sert bir iç dünya, baskı, agresyon, psikolojik yük, zaman zaman da anne kaynaklı kırılmalar verebilir. Özellikle 11 enerjisi çocuklukta psikolojik sertlik, baskı, korku ve yoğun gerilim taşıyabilir. Bunun yanında 12 ve 8 temaları da hakkına girilme, fedakârlık, insanın kendi sınırlarını koruyamaması ve kendini fazla verme halini gösterir. Dördüncü ay doğumları ayrıca ata hattıyla çok bağlantılıdır; bu insanlar çoğu zaman baba soyunun yarım kalan gücünü taşır, atanın yapamadığını tamamlama göreviyle gelir. Hayat karmanızdaki 7 de bu yüzden çok önemli; çünkü 7 burada savaş, mücadele, yolda kalma korkusu, hedefe giderken engellenme, kök çakrada sarsıntı ve atalar hattında savaş, göç, ayrılık, kayıp gibi izler bırakır. Soyunuzda savaşa gidip dönmeyenler, göç edenler, sert kader kırılmaları yaşayanlar varsa bu enerji sizde de "tam hedefime giderken sanki bir şey oluyor" duygusu yaratır. O yüzden burada yalnızca sizin bireysel hikâyeniz yok; ata ve ana soylarının yükleri de var.

Bir başka çok önemli nokta da şu: sizde kadınlık enerjisi ile eril güç aynı anda çalışıyor. 3 kadınlığı, üretkenliği, dişil enerjiyi; 4 ise imparatoru, düzeni, kontrolü, gururu ve sertliği temsil ediyor. Bu yüzden siz bazen kadın olarak çok hassas, fedakâr ve verici; bazen de çok dik, gururlu, kendi bildiğini yapan, kontrolü elden bırakmak istemeyen biri olabilirsiniz. Kadında 4, 5, 8 ve 19 çok yükseldiğinde onu yumuşatmak gerekir; çünkü aksi halde dişil enerji bastırılır, kadın sertleşir, istemese de eril tavır geliştirir ve ilişkilerde zorlanır. Sizde bu potansiyel var ama tamamen sertleşmiş değil; çünkü diğer rakamlar bunu dengelemiş. Yine de bu yüzden hem "güçlü olayım" diyorsunuz hem de derinde sevilmek, görülmek, takdir edilmek istiyorsunuz.

15 burada çok dikkat çekici. 15 karizma verir, dikkat çektirir, ortamda fark edilme gücü verir, lüksü ve güzel olanı sevdirebilir. Aynı zamanda 15'in gölge tarafı bağımlılıklardır. Bu bağımlılık her zaman kötü alışkanlık olmak zorunda değil; marka tutkusu, lüks tutkusu, gösteriş, beğenilme ihtiyacı, dikkat çekme arzusu da olabilir. Sizde para enerjisi yok değil; hatta güçlü. Ama para sizde sadece maddi güvenlik için değil, estetik, kalite ve kendini iyi hissetme alanı için de çalışıyor. Burada bütçe planlaması öğrenilmezse kişi bazen son parayı bile "iyi olsun" diye harcayabilir. Bu yüzden sistem size şunu öğretmek istiyor: güzellikten vazgeçmeden denge kurmak.

19 enerjisiyle çocuklukta ailenin gözdesi olma, özel görülme, dikkat çekme, merkezde olma ihtiyacı çalışır. 19'un pozitif tarafı liderlik, güneş gibi parlamak, görünür olmak, insanlara ışık olmak; negatif tarafı ise ego, narsistik kırılganlık, "beni neden yeterince sevmiyorlar" duygusu, ilgi görmediğinde içten daralma ve kontrol ihtiyacıdır. Eşinizden yoğun sevgi beklemek, sevginin açık açık gösterilmesini istemek, dışarıdan gelen sevgiyi kendi değerinize ölçü yapmak da buradan gelir. Fakat harita diyor ki sizin dersiniz dışarıdan sevgi beklemek değil; önce kendi içinizdeki değeri görmek. 8 misyonu burada tam olarak bunu söyler: denge. Yani sevgi yalnızca dışarıdan alınan bir şey olursa insanın hayatı hep eksik kalır. Siz kendi içinizdeki güneşi tanımadan karşı taraftan tam onay alamazsınız. Eşiniz de bu noktada sizi aynalıyor; sizi cezalandırmak için değil, kendinizi sevme dersinizi göstermek için.

Bu haritada 2 çok güçlü görünmese de tamamen yok değil; ama empatiyi, karşı tarafın geçmişini ve duygusal yapısını düşünmeyi bilinçli olarak büyütmek gerekiyor. Çünkü 3, 4 ve 19 bir araya geldiğinde insan ister istemez "ben" merkezli düşünebilir. Harita da burada sizi 8'e, yani başkalarının hakkına saygı duymaya, adaletli olmaya, kınamamaya ve dengeye çağırıyor. Ne kınarsanız, neyi yargılarsanız dönüp size gelir. Bu yüzden özellikle anne babaya, eşe, akrabalara içten içe kızgınlık ve hüküm kurma enerjisini azaltmanız lazım.

Sizin için rakamlar, sistemler, hesap, analiz, mantık çok önemli. 4 ve 8 bir araya gelince kişiyi sadece sezgiyle çalışan biri yapmaz; aksine, somut bilgi, sonuç, ispat, sistem ve mantık aratır. Bu yüzden size yalnızca "gözünü kapat, bırak, hisset" tarzı şeyler çoğu zaman yeterli gelmez. Sizin beyniniz neden-sonuç ister. O yüzden numeroloji, hesap, kod, analiz, hatta kısa süreli de olsa rakamlarla ilgili bir eğitim size çok iyi gelir. Bu illa hayat boyu yapacağınız ana meslek olmak zorunda değil; ama zihninizin açılması, kendi yolunuzu anlamanız ve mantığınızın doyurulması için çok gerekir. Çünkü bu haritada 5 de öğrenmek, öğretmek ve bilgi paylaşmak istiyor. Bir gün bu öğrendiklerinizi başkalarına aktarma potansiyeliniz de var. Yani siz sadece öğrenen değil, ileride öğreten bir enerjiye de dönüşebilirsiniz.

28 yaş sonrası özellikle 18 aktive olduğu için spiritüel alanlar, gizli bilgiler, astroloji, numeroloji, semboller, kodlar, bilinçaltı, su çalışmaları, ritüeller, dualar ve sezgiler hayatınıza daha çok girebilir. 18 hem korku hem sezgi taşır. Bir yandan vesvese verebilir, kuruntu verebilir, "ya şöyle olursa" diye düşündürebilir; diğer yandan da çok güçlü manifest ettirir. O yüzden bu dönem sizin için çok kıymetli. Aklınızdan geçen şeylerin olması, bazı şeyleri önceden hissetmeniz, belli konuların bir anda önünüze düşmesi tesadüf değil. 18 bunu yapar. Bu yüzden korkularınızı boşaltmanız ve su elementiyle çalışmanız çok faydalı olur.

Bu dönemde size verilecek en önemli görevlerden biri korkularınızı yazmak ve bırakmaktır. Çünkü 18 aktifken korkular zihne doluşur; 7 ise hedefe giderken geri çeker; 22 ise hevesle başlatıp sonra bırakma eğilimi verebilir. Bu yüzden her gün kâğıda "özgüvensiz olmaktan korkuyorum, haksızlığa uğramaktan korkuyorum, kendimi ifade edememekten korkuyorum, kuracağım işi batırmaktan korkuyorum, anlaşılmamaktan korkuyorum" gibi içinizden gelen her şeyi yazmak, sonra bunları ruhunuzdan, zihninizden, bedeninizden ve ana rahminden serbest bıraktığınızı söylemek çok güçlü bir sembolik çalışmadır. Bu sizin zihninize "ben artık sadece korkan değil, korkusunu dönüştüren biriyim" mesajı verir.

Su da sizin için çok önemli çalışır. Sabah aç karnına suya "ben kadınım, kadın başlangıcımı kabul ediyorum, hedeflerime rahatlıkla giderim, parlayacağım, destekleniyorum, adaletli insanlarla karşılaşıyorum, gücümün farkındayım" gibi cümleler okumak size iyi gelir. Sonra kendi özel isteklerinizi de eklersiniz. Bu size sadece ruhsal huzur vermez; 18 aktif olduğu için aynı zamanda zihninizi yeni olasılıklara açar. Bu tür çalışmalar size saçma değil, tam tersine haritanıza uygun gelir; çünkü sizde 18 bunu destekliyor.

Soylarla ilgili çalışmalar da burada çok önemli. Ata ve ana soylarınızın adına sadaka vermek, özellikle yetim, kimsesiz, anne-baba himayesinden mahrum çocuklara yardım etmek çok büyük açılım getirir. Çünkü 18 ve 8 bunu ister; 7 de savaşta kalan, hedefe ulaşamayan, yolu yarım kalan ruhların onurlandırılmasını ister. Aynı şekilde savaşa gidip dönmeyenler, göçte kaybolanlar, mezarı olmayanlar, kazada ölenler için ağaç dikmek çok anlamlıdır. Meyvesiz ağaç, özellikle bu tür ruhları onurlandırmak için sembolik olarak güçlü çalışır. Buradaki niyet şudur: "Soylarımın yaşadığı savaş, hedefsizlik, ani ölüm, kayıp ve yarım kalma enerjilerini artık sevgiyle görüyorum ama kendi kaderimi bunlardan özgürleştiriyorum." Bu cümle sizin için anahtar.

Dünyaya gelmeyen çocuklarla ilgili enerji de haritada önemli. Hem soy hattında düşen ya da doğmayan çocuklar, hem de sizin kendi yaşadığınız kayıplar ayrı bir yük oluşturabilir. Bunun için de yine doğaya bir ağaç armağan etmek, dünyaya gelmeyen çocukların ruhuna sadaka çıkarmak ve onların adına hasta ya da engelli çocuklara yardım etmek çok şifalı olur. Bu, suçluluk enerjisini yumuşatır ve içteki düğümü çözer.

Anne ve baba için ayrı ayrı hayvan beslemek de yine bu haritaya çok uygun. Sokak hayvanlarına "babamın adına", "annemin adına" diye niyet ederek yiyecek vermek hem 2'nin, hem 18'in, hem 8'in enerjisini yumuşatır. Çünkü bu, içten içe anne-babayla olan karmik borcun kabulü ve yargının bırakılması anlamına gelir. Buradaki esas cümle şudur: "Bu dersi aldım, kabul ettim ve bitiriyorum." Bu cümle sizin hayatınızda çok şey çözer.

7 ve 11 aynı zamanda fiziksel hareket ister. Yani sadece dua, niyet, yazma değil; bedenin de işin içine girmesi gerekir. Günde belirli adım atmak, spor yapmak, hareket etmek sizin için zorunluya yakın. Çünkü 7 bedenin disiplinini ister. Hedefe giden insanın bedeninin de yola eşlik etmesini ister. Sizde bazen büyük niyetler olup fiziksel aksiyon düşebilir. O yüzden sistem sizden hareket istiyor.

Bir başka önemli sembolik çalışma da güneş ve ayı hayatınıza almaktır. Çünkü 19 güneş, 18 ay; biri ata hattını, biri anne hattını temsil eder. Evde ya da telefonda tam bir güneş ve tam bir ay resmi bulundurmak, hatta yanında mutlu bir çocuk figürü olması sizin bilinçaltınıza "anne ve baba ışığı birleşti, ben de o sevginin içinden kök salıyorum" mesajını verir. Özellikle anneanne ya da farklı aile konfigürasyonlarında büyüyen çocuklarda bu iç yapı eksik kalabilir. Sizde de bilinçaltını yeniden düzenlemek için bu tarz görsel semboller iyi çalışır. Gece kendinizi bir çınar ağacı gibi hayal edip ayın ve güneşin size ışık verdiğini, yağmurun üzerinize indiğini, köklerinizin toprağa yayıldığını düşünmek köklenme açısından çok güçlü olur.

8 size sürekli şunu söylüyor: hakkına girme, kendi hakkına da girme. Yani yalnızca başkalarını yargılamak değil, kendini aşırı suçlamak, kendini geri plana atmak, fazla fedakârlıkla kendi hakkından vazgeçmek de bir adaletsizliktir. Sizde 12 olduğu için bunu yapma riski var. Sonra da kimse teşekkür etmediğinde kırılabilirsiniz. O yüzden öğrenmeniz gereken şey fedakârlıkla öz değeri karıştırmamak.

İş ve para tarafında ise harita çok net: sizin yolunuz başkasına bağımlı klasik düzende çalışmaktan çok, kendi sisteminizi kurmak. 4, 3, 7 ve 22 bunu çok açık söylüyor. Kendi işiniz, ama özellikle kadınlara ve çocuklara dönük bir alan; takım kurabileceğiniz, insanları bir araya getirebileceğiniz, sözünüzle etkileyebileceğiniz, ama saat bazlı kölelik yapmak zorunda kalmayacağınız bir sistem. Bunun içinde satış da var, etki de var, konuşma da var, yönlendirme de var; ama bunu mutlaka adaletle, prosedürle, belgelerle yapmanız gerekir. Çünkü 8 resmi evrak, sözleşme, imza, kanun ve düzen ister. Siz herhangi bir iş kurarsanız "nasıl olsa olur" diye değil; kayıtlı, sözleşmeli, sistemli gitmelisiniz. İlişkide de aynı şey geçerli. 8'i olan insan için resmiyet, netlik, sınır çok önemlidir. Belirsiz ve gayriresmî alanlar 8'i bozar.

Sözünüzü kullanmak da bu haritanın ayrı bir dersi. Boğaz enerjisi tam desteklenmezse kişi kendini anlatmakta zorlanır, tam ifade edemez, içinde olanı doğru biçimde dışarı veremez. Bu yüzden ses çalışmaları, kitap okumak, yüksek sesle konuşmak, hatta şarkı söylemek bile size iyi gelebilir. Çünkü siz sadece düşündüğünüzü bilen değil, onu dışarı da güçlü çıkarabilen biri olduğunuzda açılırsınız.

8 etkisi yüzünden terapi ya da spiritüel alan size ancak mantığınız da ikna olursa tam fayda verir. Bu yüzden sizin için mistik olanla mantıklı olanın birlikte yürümesi gerekir. Ne yalnızca maddiyat, ne yalnızca ruhsallık. Harita bunu çok net söylüyor: maddiyat ile ruhanilik arasında denge kurmalısınız. Sadece para derseniz ruhunuz aç kalır. Sadece ruhsallık derseniz potansiyeliniz yere inmez. Siz hem iş kurmalı, hem de duayla, niyetle, sembolik çalışmalarla, Yaradan'la bağınızı canlı tutmalısınız. Aksi hâlde hayat dengesizleşir.

Bu dönemde dikkat etmeniz gereken başka bir şey de gizli işlerdir. 18 aktifken gizli kalan şeyler açığa çıkar. O yüzden siz de gizli iş çevirmemeli, planlarınızı doğru zamanda doğru şekilde şeffaflaştırmalısınız. Ama aynı zamanda size karşı gizlenen şeylerin de açığa çıkacağı bir dönemdesiniz. 18 bunu yapar. Ayrıca 18 gizli ilimleri de sever. O yüzden numeroloji, astroloji, kodlar, haritalar, semboller, ruhsal sistemler sizin için sadece hobi değil, aynı zamanda kendi kapınızı açan anahtarlardır.

Son olarak şunu çok net söyleyebilirim: bu dönem hayatınızda büyük bir dönüş getiriyor. 22 geldiğinde insanın hayatında sıfırdan bir başlangıç doğar. Daha önce yapmadığı bir yola girer. Korksa da girer. Çünkü 22 ayağının altını her zaman tam görmez ama yine de gider. Hayat da size diyor ki: bilinmeyene adım at. Sıfırdan bir şey başlat. Ama bunu korkuyla değil, bilinçle, dengeyle, soylarınızı onurlandırarak, kadınlığınızı kabul ederek, kendi hakkınızı koruyarak ve ruhsal bağınızı koparmadan yap. O zaman bu harita sizi gerçekten çok güzel bir yere taşır.`
  },

  {
    birthDate: "08.08.1970",
    text: `Sizin kök çakranız 17'ye denk geliyor. Geçmiş yaşamda egolu, kibirli, meşhur birisi olmuşsunuz; 17 yıldız enerjisidir. Ama burası negatif çalıştığında kişi görünmek istemez, görünür olması gereken yerde saklanır. Sizin paraya giden ve köklenme enerjinizde umut, şans ve yıldız var. Yıldızınızı parlatmanız gerekiyor. Bir yeteneğiniz var; 17'lerin Tanrı'dan gelen bir yeteneği olur. Ses mi, el kabiliyeti mi? Bir şey var. Peki bu yeteneği açığa çıkarabildiniz mi?

Misyon 11 diyor ki: "Hayattaki gücünü bulabildin mi? Sınırlarını çizebildin mi?" 11'in negatifi baskı, şiddet ve agresyondur. O agresyonu hayatından çıkarabildin mi? Hayatına çektiğin insanlar, özellikle 16'dan dolayı, sert ve yıkıcı karakterler olabilir. Soğuk ve yıkmaya hazır... Baba soyu erkeklerin yaşadığı manevi karma 16. Bir şeyleri yıkıp dağıtmışlar, baskı yapmışlar. Evliliği dağıtmış olabilirler, fiziksel şiddet göstermiş olabilirler. Ya da bir yangın, bir ateş... Birisi yanarak mı öldü? Çünkü 16 ateş elementidir. Parasını dağıtan, evinden uzak düşen ata soyları var.

Baba soyu atalarınızda agresif, kızdı mı her şeyi dağıtıp döken, hatta intihar bile edebilecek karakterler olabilir. Çünkü 16, kuleden atlamayı da temsil eder. 16 biraz zor rakamdır; yüzde 90 boşanma verir. Çok nadiren boşanmazlar. Zaten bu 9'lar ve 22'ler sizde aşırı özgürlük hissi yaratıyor. Özgür olmak, kendinizle mutlu olmak ve akıllı insan arayışı... 9'a sadece aşk yetmez, ruhun olgunluğu ve paylaşım önemlidir.

Karmanızda 13 olduğu için belki konfor alanınızı zorluyorsunuzdur. Çünkü 13 alıştığı şeyi bırakamaz, 22 ise başlattığı şeyi bazen yarım bırakır. 22'lerin içinde çocukluğunu yaşamamış çocuklar vardır. Erken büyümek zorunda kalmış, baskı ve kısıtlanma görmüş kadınlardır bunlar. Çocukları küçük yaşta çok sık hastalanabilir. 22'nin konusu çocuklardır.

Sizin rakamlarınızda hem 22 hem 9 var; yani içinizde hem bir çocuk hem de çok olgun bir ruh var. Hayat karmanız 8 olduğu için hayatı dengeye getirmekte zorlanıyorsunuz. Dişil enerji haritada zayıf; anneden geçememiş. Başarı sayınızda 3 ve 7 var; bu enerji belli yaşlarda tekrar tekrar gelmiş. Aynı 3 ve 7 en son evrede tekrar geliyor. Bu, aynı döngünün tekrarlandığını gösterir.

Artık 4. evredesiniz. Sisteme gelmişsiniz: "Artık bu yaşımda aşkı, 6'yı bulacağım." 6 aşk kartıdır. Sistem artık bir aşkı bulmanızı söylüyor. Ama 7 diyor ki hedefine tam gidememişsin. Hedef ne? Kadınlık, dişilik ve kendi işini kurmak. Sistem size kendi işinizin başında bir kraliçe enerjisi, bereket enerjisi veriyor. 7 hem savaştır hem hedeftir. Seyahatler yapabilir, araba alabilir, beklediğiniz hedeflere ulaşabilirsiniz. Ama enerji negatiften çalışırsa hedefe gidememek de olur. Şu ana kadar enerjinizi pozitife getirmekte zorlanmışsınızdır çünkü 16 ve 8 çok yoğun.

Bakın, 30 yaşa kadar olan ilk döngünüzde 16 ve 22'yi yaşamışsınız. 16 yıkımdır; bir şeyler yıkılmış olabilir. 13 de değişimi kabullenmekte zorlanır. 8 ve adalet demektir. Bir yerde dengesizlik var; ya çok çalışıyor kadınlığınıza zaman ayırmıyorsunuz, ya bir şeyler eksik. 9 ile 22 zıttır; biri çocuk gibi eğlenmek ister, diğeri erken olgunlaşmıştır.

Sizin yolunuz karma yasalarını öğrenmekten geçer. Numerolojiyi en iyi 8'ler yapar ama en çok da onlar zorlanır çünkü çok mantıksaldırlar. Hep sonuca odaklanırlar, sürece değil. Akışa bırakamazlar, hep kontrol. Ağustos doğumlu kadınlarda "güçlü olmak zorundasın" enerjisi vardır. Hiç düşeceğinizi göstermezsiniz. Ama bu kadar güç, kadınlığınızı engelliyor. İçsel yalnızlık duygusu (9 derviş enerjisi) gitmez. Karma 9, büyük işler görmeyi, derin bilgileri insanlara aktarmayı gerektirir. Yabancı ülkeye taşınmak bile bir transformasyondur; 13 bunu yapmış olabilir.

Misyon 11; agresyon ve şiddet gördünüz mü hayatınızda? Büyük baskılar, sert dönemler? Kendiniz sinirlenince her şeyi dağıtır mısınız? Aslan kükremesi yapar mısınız? 11; vurduğu veya kırdığı zaman rahatlar. 11 fiziksel gücü, cinsel enerjiyi ve aşkı temsil eder. 11'ler fiziksel olarak çok dirençlidir ama siz artık 4. evredesiniz. Sistem soruyor: "Hayatını ne kadar dengede yaşadın? Anne babayı yargıladın mı?" 8'in yaptığı küçücük bir yargı ona iki kat döner. Kanunları çiğnemek, başkasının hakkına girmek... Bunlara çok dikkat etmek lazım.

8 aynı zamanda alma-verme dengesidir. Karmanızda olduğu için sizin de hakkınıza çok geçilmiştir. Ama ruhunuz geçmişte karma yarattığı için şimdi mağdur tarafı oynuyor olabilir. Başkasının karmasına müdahale etmeyin; yardım edeceğim derken onun tekamülüne engel olmayın. 16'dan dolayı çok vericisiniz, alıcı değilsiniz. Bir kadın çok verici olduğunda değeri bilinmez.

Anneniz erken yaşta kocasız kalmış olabilir. İşte 9 atasal geliyor. Soyda hiç evlenmeyenler, dul kalanlar, kendini kapatanlar vardır. 13'ler normal olmayan ölümleri gösterir. Soyda intihar olabilir. İşte 13 ve 16 intiharı, ani ölümü, kazayı gösterir. 16 enerjisinde her şey aniden olur; iyi haber de kötü haber de. Sistem diyor ki: "Kibrinden kurtul, 'Bana nasıl yaparlar?' deme. Sen de başkalarına yaptın ki yaşıyorsun."

Çocuk ölümü de olabilir; 22 ve 13 bunu gösterir. Soyda 10 çocuktan sadece birkaçı yaşamış, diğerleri bebekken ölmüş olabilir. İşte şifreniz; 22-13 çocuk ölümünü gösterir. Bir de hapishane veya kendini eve kapatma durumu... Soyda sakat doğumlar, erken ölen çocuklar, yalnız kadınlar, haksız bölünen mallar... Siz 8-8 gelmişsiniz ki bu adaleti düzeltesiniz. 8'ler bırakamaz, tutunur; 13 ise unutamaz. Bu yükler ruhunuza hastalık yapar, bırakmanız lazım.

Atalarınızı onurlandırmalısınız. 9'un o yalnızlık duygusundan çıkmak için meyvesiz bir ağaç dikin (çam gibi). Niyet edin: "Atalarımdaki evlenmemiş, çocuksuz, yalnız, erken ölen tüm ruhlar için bu ağacı hediye ediyorum. Onları görüyorum, ruhları ışığa gitsin. Kendi kaderimi bu yalnızlık duygusundan azat ediyorum." Ayrıca yaşlıları sevindirin, onlara fiziken veya madden yardım edin. Kusurlu, hasta çocuklar için bağış yapın ama niyetinizi atalarınıza armağan ederek yapın. "Annem, babam ve 7 kuşak atalarımın günahları için bu sadakayı veriyorum" deyin.

Sokak hayvanlarını bir kez babanız, bir kez anneniz adına besleyin. Sevabı onlara gitsin deyin. Üst soyları şifalandırırsanız çocuklarınız da şifalanır. Sizin bu döneminizde kadın enerjinizi çıkarmanız lazım. 8'in o aşırı mantıklı ve kontrolcü halinden çıkıp akışa güvenin. Dokuzun o saklı bilgisini paylaşın.

Siz de eğitimlerinizi saklamayın. "İnsanlar ne der?" diye çekinmeyin, bu egodur. 9 mükemmeliyetçidir; "ya en iyisi olsun ya hiç olmasın" der ve erteler. Ama misyonunuz 6; sosyal ol, konuş, dışa dön. 17; bir yıldız gibi parla. Bir sayfa açın, küçük videolarla başlayın. Her sabah bir bardak suya olumlu niyetler (kadınlığımı kabul ediyorum, adalet beni buluyor, güçlüyüm vb.) söyleyip için. 21 gün yapın.

Sistem size bağırıyor: "Konfor alanından çık, dengeye gel!" Siz atalarınızı ve kendinizi şifalandırırsanız hayatınızdaki diğer insanlar da rahatlayacak. Şifa olsun.`
  }
];
